# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Configure AWS credentials from vikas-test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_SECRET_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-2
      # Runs a single command using the runners shell
      - name: Install requirements and Make a Deployment package
        run: |
          pip install -r requirements.txt -t .
          rm -rf operations.zip
          zip -r operations.zip  . -x  '*.git*'  '*.venv*'  *.zip *.txt




      # Runs a set of commands using the runners shell
      - name: upload   deployment package to s3
        run: |
          aws s3 cp operations.zip s3://deployment-package1
 
      - name: Update  deployment package for lambda from S3 
        run: |
            aws lambda update-function-code --function-name  increment-operation --s3-bucket "deployment-package1" --s3-key  "operations.zip"  
            aws lambda update-function-code --function-name  square-operation --s3-bucket "deployment-package1" --s3-key  "operations.zip" 
            aws lambda update-function-code --function-name  decrement-operation --s3-bucket "deployment-package1" --s3-key  "operations.zip"  
  

    
    
